### ISSUE TITLE
[Layout file Structure]

### ISSUE THREAD

**Issue by diaztran** [hardik-vala/mahjong-solitaire#3]
Hello!
I spent hours reading the code and layout and comparing it with GameBoard but still don't understand the meaning of the layout file's structure. Can you please explain or specify which part of the document describes the structure of the layout file?
Thank you very much.

**Comment by hardik-vala** [comment]
I feel your pain. Even I’m having a difficult time deciphering the layout definition. I’m out of town right now and don’t have the bandwidth to dig deeper this week, so it’d be great if you can wait until next week for an answer. If not, the answer is probably somewhere on the [course website](http://www.sable.mcgill.ca/~clump/comp303/) (this project was a part of the evaluation for the software development course I took in college) in case you want to check that out.

**Comment by diaztran** [comment]
Thank you for taking the time to read the issue.
Last night, after spending more time reading all of your code, I understood the whole idea as well as the data structure of the project.
Thank you for this public project.
Best regards,
